# Generated by Django 4.2.27 on 2026-04-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Admin label for reusing this CTA.', max_length=120)),
                ('heading', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('primary_label', models.CharField(blank=True, max_length=80)),
                ('primary_url', models.CharField(blank=True, help_text='External URL or local path.', max_length=255)),
                ('secondary_label', models.CharField(blank=True, max_length=80)),
                ('secondary_url', models.CharField(blank=True, help_text='External URL or local path.', max_length=255)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal/admin title for this page.', max_length=255)),
                ('slug', models.SlugField(help_text="URL slug, for example 'about' creates /about/. The homepage can use 'home'.", max_length=255, unique=True)),
                ('template', models.CharField(choices=[('homepage', 'Homepage'), ('standard', 'Standard page'), ('service', 'Service / landing page'), ('simple', 'Simple text page'), ('contact', 'Contact / CTA page')], default='standard', help_text='Controls the layout. Content still comes from editable sections below.', max_length=40)),
                ('h1', models.CharField(blank=True, help_text='Optional page-level H1. Leave blank if the first hero section owns the H1.', max_length=255, verbose_name='H1 heading')),
                ('intro', models.TextField(blank=True, help_text='Optional short intro shown by standard templates.')),
                ('seo_title', models.CharField(blank=True, help_text='Meta title. Defaults to the page title.', max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('social_image_url', models.URLField(blank=True, help_text='Optional Open Graph/social sharing image URL.')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical URL override.')),
                ('noindex', models.BooleanField(default=False, help_text='Ask search engines not to index this page.')),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_homepage', models.BooleanField(default=False, help_text='Serve this page at /.')),
                ('show_navigation', models.BooleanField(default=True)),
                ('show_footer', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Useful when listing pages or link cards.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich text'), ('card_grid', 'Card grid'), ('benefit_list', 'Icon / benefit list'), ('cta', 'CTA block'), ('testimonials', 'Testimonial block'), ('faq', 'FAQ block'), ('quote', 'Quote block'), ('link_cards', 'Link cards / child page cards'), ('image_text', 'Image + text split'), ('gallery', 'Simple gallery / image block')], default='rich_text', max_length=40)),
                ('name', models.CharField(blank=True, help_text='Admin-only label. Useful when a page has several sections of the same type.', max_length=120)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('image_position', models.CharField(choices=[('left', 'Image left'), ('right', 'Image right')], default='right', max_length=10)),
                ('is_full_height', models.BooleanField(default=False, help_text='Useful for a splash-style hero. Other section types ignore this.')),
                ('primary_cta_label', models.CharField(blank=True, max_length=80)),
                ('primary_cta_url', models.CharField(blank=True, help_text='External URL or local path.', max_length=255)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=80)),
                ('secondary_cta_url', models.CharField(blank=True, help_text='External URL or local path.', max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.page')),
                ('primary_cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_section_ctas', to='website.page')),
                ('reusable_cta', models.ForeignKey(blank=True, help_text='Optional shared CTA snippet. CTA sections can use this instead of local fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.calltoaction')),
                ('secondary_cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_section_ctas', to='website.page')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='YogaCat', max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('logo_alt', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=80)),
                ('contact_address', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('default_meta_title', models.CharField(blank=True, max_length=255)),
                ('default_meta_description', models.CharField(blank=True, max_length=160)),
                ('default_social_image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name or short label.', max_length=80)),
                ('image_url', models.URLField(blank=True)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, help_text='External URL or local path.', max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_items', to='website.page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.pagesection')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_area', models.CharField(choices=[('primary', 'Primary navigation'), ('footer', 'Footer navigation')], default='primary', max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, help_text='External URL or local path. Ignored if page is set.', max_length=255)),
                ('opens_new_tab', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='website.page')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='website.sitesettings')),
            ],
            options={
                'ordering': ['nav_area', 'sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='primary_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cta_snippets', to='website.page'),
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='secondary_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_cta_snippets', to='website.page'),
        ),
    ]
