# Generated by Django 4.2.27 on 2026-04-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('version', models.CharField(default='1.0', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(help_text='JSON Schema used for OpenAI Structured Outputs.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='body',
            field=models.TextField(blank=True, help_text='Plain text only. Do not store raw HTML.'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='body',
            field=models.TextField(blank=True, help_text='Plain text only. Use blank lines for paragraph breaks.'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='intro',
            field=models.TextField(blank=True, help_text='Plain text only. Do not store raw HTML.'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='body',
            field=models.TextField(blank=True, help_text='Plain text only. Do not store raw HTML.'),
        ),
        migrations.CreateModel(
            name='ContentGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('model', models.CharField(default='gpt-4.1-mini', help_text='OpenAI model used by the generation command.', max_length=80)),
                ('brief', models.TextField(help_text='Client/site brief. Include audience, offer, tone, pages needed, and constraints.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('applied', 'Applied to draft pages'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('generated_content', models.JSONField(blank=True, help_text='Schema-valid generated content. Applying it creates draft pages and structured sections.', null=True)),
                ('replace_existing_sections', models.BooleanField(default=True, help_text='When applying generated content, rebuild sections for pages included in the generated payload.')),
                ('replace_navigation', models.BooleanField(default=True, help_text='When applying generated content, replace navigation with generated navigation.')),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_schema', models.ForeignKey(blank=True, help_text='Schema used for OpenAI Structured Outputs. Leave blank to use the active brochure schema.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.contentschema')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
