name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Google Container Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/frome-digital/fd

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fd \
            --image gcr.io/frome-digital/fd \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --set-env-vars SECRET_KEY='${{ secrets.SECRET_KEY }}' \
            --set-env-vars GA_ID=${{ secrets.GA_ID }}
